const actionTypes = {
    FETCHING_START: "FETCHING_START",
    FETCHING_SUCCESS: "FETCHING_SUCCESS",
    FETCHING_END: "FETCHING_END",
    ADD_TO_CART: "ADD_TO_CART",
    ADD_TO_WISHLIST: "ADD_TO_WISHLIST",
};

export default actionTypes;
